--- 
abstract: rule to match on file age
author: Pedro Figueiredo <pedro.figueiredo@sns.bskyb.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: File-Find-Rule-Age
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime: 0.42
  File::Find::Rule: 0.30
version: 0.001.001
